use_frameworks!

platform :ios, '10.0'

target 'ReusableSlidersLibrary_Example' do
  pod 'ReusableSlidersLibrary', :path => '../'

  target 'ReusableSlidersLibrary_Tests' do
    inherit! :search_paths

    
  end
end
